### ISSUE TITLE
missing 2000 block from peers

### ISSUE THREAD

**Issue by bscwinner** [ServerContainers/bsc#1]
bscscan lastest block: 6818555
missing 2000 block from peers

currentBlock: 468672,
highestBlock: 6816728 (don't update lastest block)

am use ec2 c5 x2large region USA

**Comment by MarvAmBass** [comment]
Hi there,

I also noticed that not all blocks get fetched.. I'm still investigating the problem 🤔.

In theory it did everything mentioned in the binance smart Chain fullnode setup.

Did you try this without docker? I somehow suspect that this will face the same problems.

Also there seams to be a build bug in the official repo 

Hope I get it running within the next days

I'll keep this open until I find something

**Comment by MarvAmBass** [comment]
Hi there, I moved from alpine to debian and was able to build it without errors - I'm currently syncing the blockchain - but it seems to work better now ;)

**Comment by MarvAmBass** [comment]
seems to be not docker related
